//Transcutaneous Electrical Nerve Stimulation (TENS)
library TranscutaneousElectricalNerveStimulation 

using FHIR

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Transcutaneous electrical nerve stimulation (regime/therapy)": '2.16.840.1.113762.1.4.1045.19'
valueset "Chronic intractable pain (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Multiple sclerosis (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
//motor function disorders
