library ChlamydiaScreening_Common version '2'

using QDM version '5.3'

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Human papillomavirus screening (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Pap Smear Tests, FPAR": '2.16.840.1.113762.1.4.1166.10'
valueset "Cervical or vaginal cancer screening; pelvic and clinical breast examination": '2.16.840.1.113762.1.4.1047.257'
