library ChlamydiaScreening_Common version '2'

using QDM version '5.3'

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "24 hr blood pressure monitoring (regime/therapy)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Labile hypertension due to being in a clinical environment (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Hypertensive disorder, systemic arterial (disorder)": '2.16.840.1.113762.1.4.1018.240'
valueset "Cardiovascular system problem (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
