library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Psoriasis (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Steroid (substance)": '2.16.840.1.113762.1.4.1010.2'
valueset "Phototherapy of skin (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Coal Tar": '2.16.840.1.113762.1.4.1010.7'
valueset "Modified Goeckerman regimen (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Ultraviolet light therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Photochemotherapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
