library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Total nephrectomy (procedure)": '2.16.840.1.113762.1.4.1018.240'
valueset "Extracorporeal shockwave lithotripsy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//lithotriptor
valueset "Ureteric stone (disorder)": '2.16.840.1.113883.17.4077.3.2008'
valueset "Kidney stone (disorder)": '2.16.840.1.113883.17.4077.3.2008'
valueset "Simple nephrolithotomy (procedure)": '2.16.840.1.113883.3.666.5.2310'
//ultrasound lithotripsy
valueset "Electrohydraulic lithotripsy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//mechanical lithotripsy
//ultrasonic lithotripsy
//Transurethral Ureteroscopic Lithotripsy
valueset "Ureteric stone (disorder)": '2.16.840.1.113883.17.4077.2.2010'
valueset "Renal stone (substance)": '2.16.840.1.113762.1.4.1010.2'
valueset "Cystoscopy normal (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'

