library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Angina (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Medical therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Drug therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Percutaneous transluminal coronary angioplasty (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Placement of stent (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Coronary bypass graft angiography (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Ejection Fraction": '2.16.840.1.113883.3.526.2.1238'
valueset "Myocardial ischemia (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Percutaneous coronary intervention (procedure)": '2.16.840.1.113883.3.3157.2000.2'
valueset "Ventricular fibrillation (disorder)": '2.16.840.1.113883.3.526.3.366'
valueset "Cardiac arrhythmia, unspecified": '2.16.840.1.113883.3.526.3.366'
valueset "Congestive heart failure, unspecified": '2.16.840.1.113762.1.4.1182.92'
valueset "Acute myocardial infarction (disorder)": '2.16.840.1.113883.3.464.1003.104.12.1001'
valueset "Cardiac intensive care unit (environment)": '2.16.840.1.113762.1.4.1110.23'
