library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Actinic keratosis (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
//skin lesions
valueset "Entire epidermis (body structure)": '2.16.840.1.113883.3.88.12.3221.8.9'
//skin cancer
valueset "Cryotherapy of skin lesion with liquid nitrogen (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//topical drug therapy,valueset "Drug therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Curettage (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Dermabrasion (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Excision (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Chemical peeling of skin lesion (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Low power laser therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Photodynamic therapy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Squamous cell carcinoma of skin, unspecified": '2.16.840.1.113883.3.464.1003.108.12.1011'
