library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)

valueset "Cancer antigen 125 (substance)": '2.16.840.1.113762.1.4.1010.2'
valueset "Extraovarian primary peritoneal carcinoma (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Carcinoma of fallopian tube (disorder)": '2.16.840.1.113883.3.464.1003.108.12.1011'
valueset "Adenocarcinoma of endometrium (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Carcinoma of endocervix (disorder)": '2.16.840.1.113883.3.464.1003.108.12.1011'
//malignant mesothelioma  valueset "Malignant mesothelioma of parietal peritoneum (disorder)": '2.16.840.1.113883.3.464.1003.108.12.1011'
//valueset "Chemotherapy (procedure)": '2.16.840.1.113762.1.4.1018.240'
//Ovarian Carcinoma
valueset "Disease Recurrence": '2.16.840.1.113762.1.4.1116.304'
