library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)

valueset "Echoencephalography, A-mode (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Echoencephalography (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//valueset "Echocardiography for determining pericardial effusion (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Ocular and Orbital Echography (A-Mode)
//Ocular and Orbital Sonography (B-Mode)
valueset "Echocardiography (procedure)": '2.16.840.1.113762.1.4.1018.240'
valueset "Pericardial effusion (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Ultrasonic guidance for pericardiocentesis (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Echocardiography, Cardiac Valve(s) (M-Mode).
//Echocardiography, Complete (M-Mode).
//Echocardiography, limited (e.g., follow-up or limited study) (M-Mode).
valueset "Pleural effusion (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Ultrasonic guidance for thoracentesis (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Ultrasonography of abdomen (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Abdominal Sonography, limited (e.g., follow-up or limited study) (B-Scan).
//Abdominal Sonography is not synonymous with ultrasound examination of individual organs.
//Renal Cyst Aspiration, by Ultrasonic Guidance.
//valueset "Aspiration of cyst using ultrasonic guidance (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Renal Biopsy, by Ultrasonic Guidance.
//Pancreas Sonography (B-Scan)
//Pancreatic Sonography has proven effective in diagnosing pseudocysts.
//valueset "Ultrasonography of spleen with contrast (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Spleen Sonography (B-Scan)
//Abdominal Aorta Echography (A-Mode).
//Abdominal Aorta Sonography (B-Scan).
valueset "Ultrasonography of retroperitoneum (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Retroperitoneal Sonography (B-Scan).
//Urinary Bladder Sonography (B-Scan).
//Urinary bladder Sonography does not include staging of bladder tumors.
//Pregnancy Diagnosis Sonography (B-Scan).
//Fetal Age Determination (Biparietal Diameter) Sonography (B-Scan).
//Placenta Localization Sonography (B-Scan).
//valueset "CT Guidance for localization of placenta of Uterus": '1.3.6.1.4.1.12009.10.2.5'
//Pregnancy Sonography, Complete (B-Scan).
valueset "Molar pregnancy (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Ectopic pregnancy (disorder)": '2.16.840.1.113883.3.600.1622'
//Passive Testing (Antepartum Monitoring of Fetal Heart Rate In the Resting Fetus).
valueset "Intrauterine contraceptive device procedure (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Pelvic mass in pregnancy (disorder)": '2.16.840.1.113883.3.464.1003.111.11.1023'
valueset "Ultrasonic guidance for amniocentesis (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Doppler ultrasonography of arterial inflow and venous outflow of abdominal, pelvic and retroperitoneal organs (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Arterial Aneurysm, Peripheral (B-Scan).
//Radiation Therapy Planning Sonography (B-Scan).
valueset "Echography of thyroid, A-mode (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Ultrasonography of thyroid and parathyroid (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Echography of breast, A-mode (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//Breast Sonography (B-Scan).
Hepatic Sonography (B-Scan).
Gallbladder Sonography.
Renal Sonography.
Two-Dimensional Echocardiography (B-Mode)
valueset "Monitoring of cardiac output using continuous esophageal doppler (regime/therapy)": '2.16.840.1.113883.3.88.12.80.28'

