library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Sweat test (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Cystic fibrosis (disorder)": '2.16.840.1.113883.3.464.1003.102.12.1002'
valueset "Peripheral vascular disease (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Sympathectomy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Sterilization procedure done (situation)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Illness (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
//Injury
valueset "Hysterectomy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Oophorectomy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Bilateral oophorectomy (procedure)": '2.16.840.1.113883.3.526.2.469'
valueset "Bilateral orchidectomy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Carcinoma of prostate (disorder)": '2.16.840.1.113883.3.464.1003.108.12.1011'
valueset "Tubal ligation done (situation)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Vasectomy (procedure)": '2.16.840.1.113883.3.88.12.80.28'
//valueset "Pregnant (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Diagnosis deferred (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
