library ChlamydiaScreening_Common version '2'

using QDM

//include otherLibrary version 'x.x' called otherLibrary
//codesystem codeSystemName : 'OID' version 'x.x'
//valueset valuesetName : 'OID' version 'x.x' codesystems{codeSystem1 , codeSystem2, etc}
//code codeName : 'OID' from codeSystemName display 'displayName'
//concept conceptName : {codeName1, codeName2, etc} display 'displayName'
//parameter parameterName (dataType or default value)


valueset "Age-related macular degeneration (disorder)": '2.16.840.1.113762.1.4.1018.240'
valueset "Nonexudative age-related macular degeneration, bilateral, advanced atrophic with subfoveal involvement": '2.16.840.1.113883.3.526.2.1641'
valueset "Exudative age-related macular degeneration, bilateral, with active choroidal neovascularization": '2.16.840.1.113883.3.526.3.1453'
valueset "Fluorescein angiography of eye (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Optical coherence tomography (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Visual acuity testing (procedure)": '2.16.840.1.113883.3.88.12.80.28'
valueset "Lesion size cannot be determined (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Multiple lesions (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Extrafoveal ocular fixation (finding)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Atrophic retina (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
valueset "Pathologic Myopia": '2.16.840.1.113883.3.526.2.1587'
valueset "Ocular histoplasmosis syndrome (disorder)": '2.16.840.1.113883.3.88.12.3221.7.4'
